springdoc:
  paths-to-match: /api/notify/**
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

###
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      connect-timeout: 30s
      timeout: 10s
      ssl:
        enabled: false


